// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBuPGQrw-CNsrP9orLotBWtZWkArTbsg',
    appId: '1:58798268354:web:6209c589bb8828f8df005b',
    messagingSenderId: '58798268354',
    projectId: 'otp-authentication-e34d3',
    authDomain: 'otp-authentication-e34d3.firebaseapp.com',
    storageBucket: 'otp-authentication-e34d3.appspot.com',
    measurementId: 'G-T5CS1FJ2ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8ymrZfc56meX8SWTJ1mufVv0-rw5TBo',
    appId: '1:58798268354:android:0122b6b979cbfa19df005b',
    messagingSenderId: '58798268354',
    projectId: 'otp-authentication-e34d3',
    storageBucket: 'otp-authentication-e34d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hy0K6Gq318GnFdAtDUctiwQElda74qI',
    appId: '1:58798268354:ios:2795caac5159a186df005b',
    messagingSenderId: '58798268354',
    projectId: 'otp-authentication-e34d3',
    storageBucket: 'otp-authentication-e34d3.appspot.com',
    iosBundleId: 'com.example.otpAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hy0K6Gq318GnFdAtDUctiwQElda74qI',
    appId: '1:58798268354:ios:5e4a50b57f3e6b41df005b',
    messagingSenderId: '58798268354',
    projectId: 'otp-authentication-e34d3',
    storageBucket: 'otp-authentication-e34d3.appspot.com',
    iosBundleId: 'com.example.otpAuth.RunnerTests',
  );
}
